# TODO: CREATE EVENT CREATION ENDPOINT
# CRITERIA: MUST BE AUTHED, AND MUST BE AN ADMIN

# TODO: CREATE EVENT READ ENDPOINT
# CRITERIA: None, anyone can retrieve event data

# TODO: CREATE EVENT UPDATE ENDPOINT
# CRITERIA: MUST BE AUTHED, AND ADMIN MUST BE APART OF ORG THAT EVENT IS UNDER

# TODO: CREATE EVENT DELETION ENDPOINT
# CRITERIA: MUST BE AUTHED, AND ADMIN MUST BE APART OF ORG THAT EVENT IS UNDER
